"""initial

Revision ID: fd958aed1db8
Revises:
Create Date: 2026-04-11 20:36:01.779463

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd958aed1db8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("court_listener_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("court", sa.String(), nullable=False),
        sa.Column("memory_text", sa.String(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cases_court_listener_id"), "cases", ["court_listener_id"], unique=True)
    op.create_table(
        "docket_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("court_listener_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedded", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("date_filed", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "court_listener_id", name="uq_docket_entry_case_cl_id"),
    )
    op.create_index(op.f("ix_docket_entries_case_id"), "docket_entries", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_docket_entries_court_listener_id"),
        "docket_entries",
        ["court_listener_id"],
        unique=False,
    )
    op.create_table(
        "docket_entry_documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("docket_entry_id", sa.String(length=36), nullable=False),
        sa.Column("pdf_url", sa.String(), nullable=False),
        sa.Column("pdf_path", sa.String(), nullable=True),
        sa.Column("downloaded", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("embedded", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["docket_entry_id"],
            ["docket_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_docket_entry_documents_docket_entry_id"),
        "docket_entry_documents",
        ["docket_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_docket_entry_documents_docket_entry_id"), table_name="docket_entry_documents"
    )
    op.drop_table("docket_entry_documents")
    op.drop_index(op.f("ix_docket_entries_court_listener_id"), table_name="docket_entries")
    op.drop_index(op.f("ix_docket_entries_case_id"), table_name="docket_entries")
    op.drop_table("docket_entries")
    op.drop_index(op.f("ix_cases_court_listener_id"), table_name="cases")
    op.drop_table("cases")
    # ### end Alembic commands ###
